#App\Entity\Product:
#  properties:
#    name:
#      - NotBlank: { message: "Le nom du produit est obligatoire." }
#      - Length: { min: 3, max: 255, minMessage: "Le nom du produit doit contenir au moins {{ limit }} caractères.", maxMessage: "Le nom du produit doit contenir au maximum {{ limit }} caractères." }
#    price:
#      - NotBlank: { message: "Le prix du produit doit être un nombre." }